name: PrScanAction
description: "Built action for PR scan"

inputs:
  snyk_key:
    description: 'Snyk API Key'
    required: false
  tools:
    description: 'Comma-separated list of tools to run (e.g., snyk, trufflehog)'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # fetch all history so multiple commits can be scanned

    - name: Set up environment
      id: setup
      shell: bash
      run: |
        echo "TOOLS=${{ inputs.tools }}" >> $GITHUB_ENV
        echo "SNYK_KEY=${{ inputs.snyk_key }}" >> $GITHUB_ENV
        mkdir -p reports
    
    - name: Set up Node.js 20
      id: setup_node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Run Snyk
      id: snyk_scan
      shell: bash
      if: contains(env.TOOLS, 'snyk')
      run: |
        if [ -z "$SNYK_KEY" ]; then
          echo "SNYK_KEY is not set"
          exit 1
        fi
        
        echo "----------Download Latest Snyk CLI-----------"
          curl -Lo ./snyk "https://github.com/snyk/snyk/releases/download/v1.1293.0/snyk-linux"
          chmod +x snyk
          ls -lrt
          echo "----------Authenticating Snyk-----------"
          ./snyk auth $SNYK_KEY
          echo "----------Snyk Scanning-----------"
          ./snyk test --all-projects --json | tee snyk-output.json
          echo $(pwd)
          node ./.github/action/snyk-data-to-json.js snyk-output.json ../report/snyk-report.json
    
    - name: Run Node.js Post-processing
      run: |
        echo $(pwd)
        node dist/index.js 
      shell: bash
